# Generated by Django 5.2.1 on 2025-05-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_itemvenda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemVenda',
        ),
    ]
